imports:
    - { resource: tables.yml }

services:
    kinerity.trackers.functions:
        class: kinerity\trackers\functions
        arguments:
            - '@auth'
            - '@config'
            - '@service_container'
            - '@dbal.conn'
            - '@language'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '%core.php_ext%'
            - '%tables%'

    kinerity.trackers.controller.main:
        class: kinerity\trackers\controller\main_controller
        arguments:
            - '@service_container'
            - '@language'

    kinerity.trackers.listener:
        class: kinerity\trackers\event\main_listener
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@controller.helper'
            - '@template'
            - '%tables%'
        tags:
            - { name: event.listener }

    kinerity.trackers.viewtracker:
        class: kinerity\trackers\operators\viewtracker
        arguments:
            - '@service_container'
            - '@language'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'

    kinerity.trackers.viewproject:
        class: kinerity\trackers\operators\viewproject
        arguments:
            - '@config'
            - '@service_container'
            - '@language'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'

    kinerity.trackers.viewticket:
        class: kinerity\trackers\operators\viewticket
        arguments:
            - '@auth'
            - '@config'
            - '@service_container'
            - '@language'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'

    kinerity.trackers.statistics:
        class: kinerity\trackers\operators\statistics
        arguments:
            - '@config'
            - '@service_container'
            - '@dbal.conn'
            - '@language'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '%tables%'
