parameters:
    tables.trackers_attachment: '%core.table_prefix%trackers_attachment'
    tables.trackers_component: '%core.table_prefix%trackers_component'
    tables.trackers_history: '%core.table_prefix%trackers_history'
    tables.trackers_post: '%core.table_prefix%trackers_post'
    tables.trackers_project: '%core.table_prefix%trackers_project'
    tables.trackers_project_auth: '%core.table_prefix%trackers_project_auth'
    tables.trackers_severity: '%core.table_prefix%trackers_severity'
    tables.trackers_status: '%core.table_prefix%trackers_status'
    tables.trackers_ticket: '%core.table_prefix%trackers_ticket'
    tables.trackers_tracker: '%core.table_prefix%trackers_tracker'
